//
//  12.swift
//  euler
//
//  Created by Matt Dickoff on 9/17/18.
//  Copyright © 2018 Matt Dickoff. All rights reserved.
//

import Foundation

class Problem12: Problem {
    var problemDefinition = """
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
    
    func calculateFactorsOf(x: Int, referenceDict:[Int:Set<Int>]) -> Set<Int>{
        var factors: Set<Int> = Set<Int>()
        for candidate in (1...x).reversed() {
            if !factors.contains(candidate) {
                if x % candidate == 0 {
                    guard let precalculatedFactors = referenceDict[candidate] else {
                        factors.insert(candidate)
                        continue
                    }
                    factors.formUnion(precalculatedFactors)
                }
            }
            
        }
        return factors
    }
    func solve() -> Answer {
        var factorMap = [Int:Set<Int>]()
        factorMap[1] = [1]
        
        var i = 2
        var triangleNumber = 3
        while true {
            let factors = calculateFactorsOf(x: triangleNumber, referenceDict: factorMap)
            if factors.count > 500 {
                break
            }
            factorMap[triangleNumber] = factors
            print("Number: \(i) \(triangleNumber) has \(factors.count) factors")
            i += 1
            triangleNumber += i
        }
        
        return Answer.init(result: triangleNumber)
    }
}

/*
 Number: 7546 28474831 has 16 factors
 Number: 7547 28482378 has 32 factors
 Number: 7548 28489926 has 32 factors
 Number: 7549 28497475 has 12 factors
 Number: 7550 28505025 has 36 factors
 Number: 7551 28512576 has 84 factors
 Number: 7552 28520128 has 112 factors
 Number: 7553 28527681 has 32 factors
 Number: 7554 28535235 has 16 factors
 Number: 7555 28542790 has 16 factors
 Number: 7556 28550346 has 32 factors
 Number: 7557 28557903 has 16 factors
 Number: 7558 28565461 has 4 factors
 Number: 7559 28573020 has 96 factors
 Number: 7560 28580580 has 96 factors
 Number: 7561 28588141 has 8 factors
 Number: 7562 28595703 has 16 factors
 Number: 7563 28603266 has 32 factors
 Number: 7564 28610830 has 64 factors
 Number: 7565 28618395 has 64 factors
 Number: 7566 28625961 has 64 factors
 Number: 7567 28633528 has 128 factors
 Number: 7568 28641096 has 144 factors
 Number: 7569 28648665 has 36 factors
 Number: 7570 28656235 has 16 factors
 Number: 7571 28663806 has 32 factors
 Number: 7572 28671378 has 16 factors
 Number: 7573 28678951 has 8 factors
 Number: 7574 28686525 has 48 factors
 Number: 7575 28694100 has 72 factors
 Number: 7576 28701676 has 12 factors
 Number: 7577 28709253 has 12 factors
 Number: 7578 28716831 has 48 factors
 Number: 7579 28724410 has 64 factors
 Number: 7580 28731990 has 96 factors
 Number: 7581 28739571 has 48 factors
 Number: 7582 28747153 has 8 factors
 Number: 7583 28754736 has 40 factors
 Number: 7584 28762320 has 160 factors
 Number: 7585 28769905 has 16 factors
 Number: 7586 28777491 has 16 factors
 Number: 7587 28785078 has 64 factors
 Number: 7588 28792666 has 16 factors
 Number: 7589 28800255 has 32 factors
 Number: 7590 28807845 has 32 factors
 Number: 7591 28815436 has 24 factors
 Number: 7592 28823028 has 48 factors
 Number: 7593 28830621 has 8 factors
 Number: 7594 28838215 has 24 factors
 Number: 7595 28845810 has 144 factors
 Number: 7596 28853406 has 48 factors
 Number: 7597 28861003 has 16 factors
 Number: 7598 28868601 has 32 factors
 Number: 7599 28876200 has 192 factors
 Number: 7600 28883800 has 96 factors
 Number: 7601 28891401 has 32 factors
 Number: 7602 28899003 has 16 factors
 Number: 7603 28906606 has 8 factors
 Number: 7604 28914210 has 72 factors
 Number: 7605 28921815 has 36 factors
 Number: 7606 28929421 has 4 factors
 Number: 7607 28937028 has 24 factors
 Number: 7608 28944636 has 48 factors
 Number: 7609 28952245 has 16 factors
 Number: 7610 28959855 has 32 factors
 Number: 7611 28967466 has 64 factors
 Number: 7612 28975078 has 32 factors
 Number: 7613 28982691 has 40 factors
 Number: 7614 28990305 has 40 factors
 Number: 7615 28997920 has 96 factors
 Number: 7616 29005536 has 96 factors
 Number: 7617 29013153 has 16 factors
 Number: 7618 29020771 has 16 factors
 Number: 7619 29028390 has 64 factors
 Number: 7620 29036010 has 32 factors
 Number: 7621 29043631 has 8 factors
 Number: 7622 29051253 has 72 factors
 Number: 7623 29058876 has 108 factors
 Number: 7624 29066500 has 48 factors
 Number: 7625 29074125 has 64 factors
 Number: 7626 29081751 has 32 factors
 Number: 7627 29089378 has 16 factors
 Number: 7628 29097006 has 16 factors
 Number: 7629 29104635 has 32 factors
 Number: 7630 29112265 has 32 factors
 Number: 7631 29119896 has 96 factors
 Number: 7632 29127528 has 96 factors
 Number: 7633 29135161 has 16 factors
 Number: 7634 29142795 has 32 factors
 Number: 7635 29150430 has 64 factors
 Number: 7636 29158066 has 32 factors
 Number: 7637 29165703 has 32 factors
 Number: 7638 29173341 has 16 factors
 Number: 7639 29180980 has 24 factors
 Number: 7640 29188620 has 96 factors
 Number: 7641 29196261 has 16 factors
 Number: 7642 29203903 has 4 factors
 Number: 7643 29211546 has 48 factors
 Number: 7644 29219190 has 192 factors
 Number: 7645 29226835 has 16 factors
 Number: 7646 29234481 has 8 factors
 Number: 7647 29242128 has 40 factors
 Number: 7648 29249776 has 20 factors
 Number: 7649 29257425 has 36 factors
 Number: 7650 29265075 has 72 factors
 Number: 7651 29272726 has 16 factors
 Number: 7652 29280378 has 16 factors
 Number: 7653 29288031 has 16 factors
 Number: 7654 29295685 has 16 factors
 Number: 7655 29303340 has 96 factors
 Number: 7656 29310996 has 192 factors
 Number: 7657 29318653 has 32 factors
 Number: 7658 29326311 has 48 factors
 Number: 7659 29333970 has 96 factors
 Number: 7660 29341630 has 32 factors
 Number: 7661 29349291 has 16 factors
 Number: 7662 29356953 has 16 factors
 Number: 7663 29364616 has 32 factors
 Number: 7664 29372280 has 128 factors
 Number: 7665 29379945 has 32 factors
 Number: 7666 29387611 has 16 factors
 Number: 7667 29395278 has 128 factors
 Number: 7668 29402946 has 32 factors
 Number: 7669 29410615 has 16 factors
 Number: 7670 29418285 has 32 factors
 Number: 7671 29425956 has 48 factors
 Number: 7672 29433628 has 24 factors
 Number: 7673 29441301 has 8 factors
 Number: 7674 29448975 has 24 factors
 Number: 7675 29456650 has 48 factors
 Number: 7676 29464326 has 48 factors
 Number: 7677 29472003 has 24 factors
 Number: 7678 29479681 has 16 factors
 Number: 7679 29487360 has 144 factors
 Number: 7680 29495040 has 72 factors
 Number: 7681 29502721 has 8 factors
 Number: 7682 29510403 has 32 factors
 Number: 7683 29518086 has 64 factors
 Number: 7684 29525770 has 64 factors
 Number: 7685 29533455 has 96 factors
 Number: 7686 29541141 has 24 factors
 Number: 7687 29548828 has 18 factors
 Number: 7688 29556516 has 72 factors
 Number: 7689 29564205 has 32 factors
 Number: 7690 29571895 has 8 factors
 Number: 7691 29579586 has 16 factors
 Number: 7692 29587278 has 48 factors
 Number: 7693 29594971 has 12 factors
 Number: 7694 29602665 has 40 factors
 Number: 7695 29610360 has 320 factors
 Number: 7696 29618056 has 64 factors
 Number: 7697 29625753 has 16 factors
 Number: 7698 29633451 has 8 factors
 Number: 7699 29641150 has 48 factors
 Number: 7700 29648850 has 192 factors
 Number: 7701 29656551 has 16 factors
 Number: 7702 29664253 has 4 factors
 Number: 7703 29671956 has 36 factors
 Number: 7704 29679660 has 144 factors
 Number: 7705 29687365 has 16 factors
 Number: 7706 29695071 has 16 factors
 Number: 7707 29702778 has 64 factors
 Number: 7708 29710486 has 32 factors
 Number: 7709 29718195 has 32 factors
 Number: 7710 29725905 has 32 factors
 Number: 7711 29733616 has 40 factors
 Number: 7712 29741328 has 60 factors
 Number: 7713 29749041 has 48 factors
 Number: 7714 29756755 has 32 factors
 Number: 7715 29764470 has 32 factors
 Number: 7716 29772186 has 16 factors
 Number: 7717 29779903 has 8 factors
 Number: 7718 29787621 has 32 factors
 Number: 7719 29795340 has 96 factors
 Number: 7720 29803060 has 48 factors
 Number: 7721 29810781 has 64 factors
 Number: 7722 29818503 has 32 factors
 Number: 7723 29826226 has 8 factors
 Number: 7724 29833950 has 48 factors
 Number: 7725 29841675 has 24 factors
 Number: 7726 29849401 has 4 factors
 Number: 7727 29857128 has 64 factors
 Number: 7728 29864856 has 128 factors
 Number: 7729 29872585 has 16 factors
 Number: 7730 29880315 has 24 factors
 Number: 7731 29888046 has 24 factors
 Number: 7732 29895778 has 32 factors
 Number: 7733 29903511 has 32 factors
 Number: 7734 29911245 has 64 factors
 Number: 7735 29918980 has 96 factors
 Number: 7736 29926716 has 24 factors
 Number: 7737 29934453 has 16 factors
 Number: 7738 29942191 has 16 factors
 Number: 7739 29949930 has 96 factors
 Number: 7740 29957670 has 48 factors
 Number: 7741 29965411 has 12 factors
 Number: 7742 29973153 has 48 factors
 Number: 7743 29980896 has 144 factors
 Number: 7744 29988640 has 72 factors
 Number: 7745 29996385 has 16 factors
 Number: 7746 30004131 has 16 factors
 Number: 7747 30011878 has 32 factors
 Number: 7748 30019626 has 128 factors
 Number: 7749 30027375 has 128 factors
 Number: 7750 30035125 has 32 factors
 Number: 7751 30042876 has 96 factors
 Number: 7752 30050628 has 48 factors
 Number: 7753 30058381 has 4 factors
 Number: 7754 30066135 has 32 factors
 Number: 7755 30073890 has 128 factors
 Number: 7756 30081646 has 16 factors
 Number: 7757 30089403 has 12 factors
 Number: 7758 30097161 has 12 factors
 Number: 7759 30104920 has 32 factors
 Number: 7760 30112680 has 128 factors
 Number: 7761 30120441 has 16 factors
 Number: 7762 30128203 has 8 factors
 Number: 7763 30135966 has 32 factors
 Number: 7764 30143730 has 32 factors
 Number: 7765 30151495 has 16 factors
 Number: 7766 30159261 has 24 factors
 Number: 7767 30167028 has 36 factors
 Number: 7768 30174796 has 24 factors
 Number: 7769 30182565 has 64 factors
 Number: 7770 30190335 has 64 factors
 Number: 7771 30198106 has 32 factors
 Number: 7772 30205878 has 32 factors
 Number: 7773 30213651 has 24 factors
 Number: 7774 30221425 has 36 factors
 Number: 7775 30229200 has 180 factors
 Number: 7776 30236976 has 240 factors
 Number: 7777 30244753 has 16 factors
 Number: 7778 30252531 has 8 factors
 Number: 7779 30260310 has 32 factors
 Number: 7780 30268090 has 32 factors
 Number: 7781 30275871 has 16 factors
 Number: 7782 30283653 has 16 factors
 Number: 7783 30291436 has 48 factors
 Number: 7784 30299220 has 144 factors
 Number: 7785 30307005 has 48 factors
 Number: 7786 30314791 has 16 factors
 Number: 7787 30322578 has 64 factors
 Number: 7788 30330366 has 32 factors
 Number: 7789 30338155 has 16 factors
 Number: 7790 30345945 has 96 factors
 Number: 7791 30353736 has 96 factors
 Number: 7792 30361528 has 16 factors
 Number: 7793 30369321 has 12 factors
 Number: 7794 30377115 has 24 factors
 Number: 7795 30384910 has 16 factors
 Number: 7796 30392706 has 32 factors
 Number: 7797 30400503 has 32 factors
 Number: 7798 30408301 has 16 factors
 Number: 7799 30416100 has 144 factors
 Number: 7800 30423900 has 144 factors
 Number: 7801 30431701 has 16 factors
 Number: 7802 30439503 has 48 factors
 Number: 7803 30447306 has 48 factors
 Number: 7804 30455110 has 32 factors
 Number: 7805 30462915 has 32 factors
 Number: 7806 30470721 has 16 factors
 Number: 7807 30478528 has 56 factors
 Number: 7808 30486336 has 112 factors
 Number: 7809 30494145 has 64 factors
 Number: 7810 30501955 has 32 factors
 Number: 7811 30509766 has 96 factors
 Number: 7812 30517578 has 96 factors
 Number: 7813 30525391 has 8 factors
 Number: 7814 30533205 has 16 factors
 Number: 7815 30541020 has 48 factors
 Number: 7816 30548836 has 12 factors
 Number: 7817 30556653 has 8 factors
 Number: 7818 30564471 has 16 factors
 Number: 7819 30572290 has 64 factors
 Number: 7820 30580110 has 192 factors
 Number: 7821 30587931 has 24 factors
 Number: 7822 30595753 has 4 factors
 Number: 7823 30603576 has 32 factors
 Number: 7824 30611400 has 96 factors
 Number: 7825 30619225 has 48 factors
 Number: 7826 30627051 has 32 factors
 Number: 7827 30634878 has 32 factors
 Number: 7828 30642706 has 16 factors
 Number: 7829 30650535 has 32 factors
 Number: 7830 30658365 has 64 factors
 Number: 7831 30666196 has 48 factors
 Number: 7832 30674028 has 96 factors
 Number: 7833 30681861 has 16 factors
 Number: 7834 30689695 has 8 factors
 Number: 7835 30697530 has 32 factors
 Number: 7836 30705366 has 32 factors
 Number: 7837 30713203 has 8 factors
 Number: 7838 30721041 has 24 factors
 Number: 7839 30728880 has 360 factors
 Number: 7840 30736720 has 60 factors
 Number: 7841 30744561 has 8 factors
 Number: 7842 30752403 has 32 factors
 Number: 7843 30760246 has 64 factors
 Number: 7844 30768090 has 64 factors
 Number: 7845 30775935 has 16 factors
 Number: 7846 30783781 has 16 factors
 Number: 7847 30791628 has 144 factors
 Number: 7848 30799476 has 72 factors
 Number: 7849 30807325 has 24 factors
 Number: 7850 30815175 has 24 factors
 Number: 7851 30823026 has 32 factors
 Number: 7852 30830878 has 16 factors
 Number: 7853 30838731 has 32 factors
 Number: 7854 30846585 has 64 factors
 Number: 7855 30854440 has 32 factors
 Number: 7856 30862296 has 80 factors
 Number: 7857 30870153 has 20 factors
 Number: 7858 30878011 has 8 factors
 Number: 7859 30885870 has 64 factors
 Number: 7860 30893730 has 64 factors
 Number: 7861 30901591 has 8 factors
 Number: 7862 30909453 has 8 factors
 Number: 7863 30917316 has 24 factors
 Number: 7864 30925180 has 72 factors
 Number: 7865 30933045 has 144 factors
 Number: 7866 30940911 has 24 factors
 Number: 7867 30948778 has 16 factors
 Number: 7868 30956646 has 64 factors
 Number: 7869 30964515 has 32 factors
 Number: 7870 30972385 has 16 factors
 Number: 7871 30980256 has 96 factors
 Number: 7872 30988128 has 48 factors
 Number: 7873 30996001 has 8 factors
 Number: 7874 31003875 has 96 factors
 Number: 7875 31011750 has 192 factors
 Number: 7876 31019626 has 16 factors
 Number: 7877 31027503 has 16 factors
 Number: 7878 31035381 has 16 factors
 Number: 7879 31043260 has 24 factors
 Number: 7880 31051140 has 96 factors
 Number: 7881 31059021 has 32 factors
 Number: 7882 31066903 has 8 factors
 Number: 7883 31074786 has 32 factors
 Number: 7884 31082670 has 128 factors
 Number: 7885 31090555 has 16 factors
 Number: 7886 31098441 has 16 factors
 Number: 7887 31106328 has 128 factors
 Number: 7888 31114216 has 128 factors
 Number: 7889 31122105 has 64 factors
 Number: 7890 31129995 has 32 factors
 Number: 7891 31137886 has 16 factors
 Number: 7892 31145778 has 24 factors
 Number: 7893 31153671 has 12 factors
 Number: 7894 31161565 has 8 factors
 Number: 7895 31169460 has 96 factors
 Number: 7896 31177356 has 96 factors
 Number: 7897 31185253 has 16 factors
 Number: 7898 31193151 has 16 factors
 Number: 7899 31201050 has 48 factors
 Number: 7900 31208950 has 24 factors
 Number: 7901 31216851 has 12 factors
 Number: 7902 31224753 has 24 factors
 Number: 7903 31232656 has 80 factors
 Number: 7904 31240560 has 320 factors
 Number: 7905 31248465 has 64 factors
 Number: 7906 31256371 has 8 factors
 Number: 7907 31264278 has 16 factors
 Number: 7908 31272186 has 32 factors
 Number: 7909 31280095 has 32 factors
 Number: 7910 31288005 has 64 factors
 Number: 7911 31295916 has 96 factors
 Number: 7912 31303828 has 48 factors
 Number: 7913 31311741 has 16 factors
 Number: 7914 31319655 has 16 factors
 Number: 7915 31327570 has 16 factors
 Number: 7916 31335486 has 64 factors
 Number: 7917 31343403 has 64 factors
 Number: 7918 31351321 has 8 factors
 Number: 7919 31359240 has 96 factors
 Number: 7920 31367160 has 144 factors
 Number: 7921 31375081 has 12 factors
 Number: 7922 31383003 has 32 factors
 Number: 7923 31390926 has 64 factors
 Number: 7924 31398850 has 48 factors
 Number: 7925 31406775 has 24 factors
 Number: 7926 31414701 has 8 factors
 Number: 7927 31422628 has 12 factors
 Number: 7928 31430556 has 36 factors
 Number: 7929 31438485 has 48 factors
 Number: 7930 31446415 has 64 factors
 Number: 7931 31454346 has 64 factors
 Number: 7932 31462278 has 16 factors
 Number: 7933 31470211 has 4 factors
 Number: 7934 31478145 has 24 factors
 Number: 7935 31486080 has 192 factors
 Number: 7936 31494016 has 32 factors
 Number: 7937 31501953 has 30 factors
 Number: 7938 31509891 has 60 factors
 Number: 7939 31517830 has 32 factors
 Number: 7940 31525770 has 32 factors
 Number: 7941 31533711 has 24 factors
 Number: 7942 31541653 has 36 factors
 Number: 7943 31549596 has 72 factors
 Number: 7944 31557540 has 96 factors
 Number: 7945 31565485 has 32 factors
 Number: 7946 31573431 has 24 factors
 Number: 7947 31581378 has 24 factors
 Number: 7948 31589326 has 8 factors
 Number: 7949 31597275 has 24 factors
 Number: 7950 31605225 has 24 factors
 Number: 7951 31613176 has 32 factors
 Number: 7952 31621128 has 128 factors
 Number: 7953 31629081 has 32 factors
 Number: 7954 31637035 has 32 factors
 Number: 7955 31644990 has 192 factors
 Number: 7956 31652946 has 96 factors
 Number: 7957 31660903 has 16 factors
 Number: 7958 31668861 has 32 factors
 Number: 7959 31676820 has 96 factors
 Number: 7960 31684780 has 48 factors
 Number: 7961 31692741 has 16 factors
 Number: 7962 31700703 has 8 factors
 Number: 7963 31708666 has 16 factors
 Number: 7964 31716630 has 128 factors
 Number: 7965 31724595 has 64 factors
 Number: 7966 31732561 has 16 factors
 Number: 7967 31740528 has 80 factors
 Number: 7968 31748496 has 80 factors
 Number: 7969 31756465 has 16 factors
 Number: 7970 31764435 has 16 factors
 Number: 7971 31772406 has 16 factors
 Number: 7972 31780378 has 32 factors
 Number: 7973 31788351 has 48 factors
 Number: 7974 31796325 has 72 factors
 Number: 7975 31804300 has 72 factors
 Number: 7976 31812276 has 24 factors
 Number: 7977 31820253 has 8 factors
 Number: 7978 31828231 has 8 factors
 Number: 7979 31836210 has 128 factors
 Number: 7980 31844190 has 128 factors
 Number: 7981 31852171 has 16 factors
 Number: 7982 31860153 has 24 factors
 */
